// Code generated by protoc-gen-go. DO NOT EDIT.
// source: maalfrid.proto

/*
Package maalfrid is a generated protocol buffer package.

It is generated from these files:
	maalfrid.proto

It has these top-level messages:
	DetectLanguageRequest
	DetectLanguageReply
*/
package maalfrid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Language codes in ISO 639-3:2007 format
type DetectLanguageReply_Language int32

const (
	DetectLanguageReply_UNKNOWN DetectLanguageReply_Language = 0
	DetectLanguageReply_NOB     DetectLanguageReply_Language = 1
	DetectLanguageReply_NNO     DetectLanguageReply_Language = 2
	DetectLanguageReply_DAN     DetectLanguageReply_Language = 3
	DetectLanguageReply_SWE     DetectLanguageReply_Language = 4
	DetectLanguageReply_ENG     DetectLanguageReply_Language = 5
	DetectLanguageReply_FRA     DetectLanguageReply_Language = 6
	DetectLanguageReply_SMA     DetectLanguageReply_Language = 7
	DetectLanguageReply_SMJ     DetectLanguageReply_Language = 8
	DetectLanguageReply_SME     DetectLanguageReply_Language = 9
	DetectLanguageReply_ABK     DetectLanguageReply_Language = 10
	DetectLanguageReply_AAR     DetectLanguageReply_Language = 11
	DetectLanguageReply_AFR     DetectLanguageReply_Language = 12
	DetectLanguageReply_AKA     DetectLanguageReply_Language = 13
	DetectLanguageReply_SQI     DetectLanguageReply_Language = 14
	DetectLanguageReply_AMH     DetectLanguageReply_Language = 15
	DetectLanguageReply_ARA     DetectLanguageReply_Language = 16
	DetectLanguageReply_ARG     DetectLanguageReply_Language = 17
	DetectLanguageReply_HYE     DetectLanguageReply_Language = 18
	DetectLanguageReply_ASM     DetectLanguageReply_Language = 19
	DetectLanguageReply_AVA     DetectLanguageReply_Language = 20
	DetectLanguageReply_AVE     DetectLanguageReply_Language = 21
	DetectLanguageReply_AYM     DetectLanguageReply_Language = 22
	DetectLanguageReply_AZE     DetectLanguageReply_Language = 23
	DetectLanguageReply_BAM     DetectLanguageReply_Language = 24
	DetectLanguageReply_BAK     DetectLanguageReply_Language = 25
	DetectLanguageReply_EUS     DetectLanguageReply_Language = 26
	DetectLanguageReply_BEL     DetectLanguageReply_Language = 27
	DetectLanguageReply_BEN     DetectLanguageReply_Language = 28
	DetectLanguageReply_BER     DetectLanguageReply_Language = 29
	DetectLanguageReply_BIS     DetectLanguageReply_Language = 30
	DetectLanguageReply_BOS     DetectLanguageReply_Language = 31
	DetectLanguageReply_BRE     DetectLanguageReply_Language = 32
	DetectLanguageReply_BUL     DetectLanguageReply_Language = 33
	DetectLanguageReply_MYA     DetectLanguageReply_Language = 34
	DetectLanguageReply_CAT     DetectLanguageReply_Language = 35
	DetectLanguageReply_CHA     DetectLanguageReply_Language = 36
	DetectLanguageReply_CHE     DetectLanguageReply_Language = 37
	DetectLanguageReply_NYA     DetectLanguageReply_Language = 38
	DetectLanguageReply_ZHO     DetectLanguageReply_Language = 39
	DetectLanguageReply_CHV     DetectLanguageReply_Language = 40
	DetectLanguageReply_COR     DetectLanguageReply_Language = 41
	DetectLanguageReply_COS     DetectLanguageReply_Language = 42
	DetectLanguageReply_CRE     DetectLanguageReply_Language = 43
	DetectLanguageReply_HRV     DetectLanguageReply_Language = 44
	DetectLanguageReply_CES     DetectLanguageReply_Language = 45
	DetectLanguageReply_PRS     DetectLanguageReply_Language = 46
	DetectLanguageReply_DIV     DetectLanguageReply_Language = 47
	DetectLanguageReply_NLD     DetectLanguageReply_Language = 48
	DetectLanguageReply_DZO     DetectLanguageReply_Language = 49
	DetectLanguageReply_EPO     DetectLanguageReply_Language = 50
	DetectLanguageReply_EST     DetectLanguageReply_Language = 51
	DetectLanguageReply_EWE     DetectLanguageReply_Language = 52
	DetectLanguageReply_FAO     DetectLanguageReply_Language = 53
	DetectLanguageReply_FIJ     DetectLanguageReply_Language = 54
	DetectLanguageReply_FIN     DetectLanguageReply_Language = 55
	DetectLanguageReply_FUL     DetectLanguageReply_Language = 56
	DetectLanguageReply_GLG     DetectLanguageReply_Language = 57
	DetectLanguageReply_KAT     DetectLanguageReply_Language = 58
	DetectLanguageReply_DEU     DetectLanguageReply_Language = 59
	DetectLanguageReply_ELL     DetectLanguageReply_Language = 60
	DetectLanguageReply_GRN     DetectLanguageReply_Language = 61
	DetectLanguageReply_GUJ     DetectLanguageReply_Language = 62
	DetectLanguageReply_HAT     DetectLanguageReply_Language = 63
	DetectLanguageReply_HAU     DetectLanguageReply_Language = 64
	DetectLanguageReply_HEB     DetectLanguageReply_Language = 65
	DetectLanguageReply_HER     DetectLanguageReply_Language = 66
	DetectLanguageReply_HIN     DetectLanguageReply_Language = 67
	DetectLanguageReply_HMO     DetectLanguageReply_Language = 68
	DetectLanguageReply_HUN     DetectLanguageReply_Language = 69
	DetectLanguageReply_INA     DetectLanguageReply_Language = 70
	DetectLanguageReply_IND     DetectLanguageReply_Language = 71
	DetectLanguageReply_ILE     DetectLanguageReply_Language = 72
	DetectLanguageReply_GLE     DetectLanguageReply_Language = 73
	DetectLanguageReply_IBO     DetectLanguageReply_Language = 74
	DetectLanguageReply_IPK     DetectLanguageReply_Language = 75
	DetectLanguageReply_IDO     DetectLanguageReply_Language = 76
	DetectLanguageReply_ISL     DetectLanguageReply_Language = 77
	DetectLanguageReply_ITA     DetectLanguageReply_Language = 78
	DetectLanguageReply_IKU     DetectLanguageReply_Language = 79
	DetectLanguageReply_JPN     DetectLanguageReply_Language = 80
	DetectLanguageReply_JAV     DetectLanguageReply_Language = 81
	DetectLanguageReply_KAL     DetectLanguageReply_Language = 82
	DetectLanguageReply_KAN     DetectLanguageReply_Language = 83
	DetectLanguageReply_KAU     DetectLanguageReply_Language = 84
	DetectLanguageReply_KAS     DetectLanguageReply_Language = 85
	DetectLanguageReply_KAZ     DetectLanguageReply_Language = 86
	DetectLanguageReply_KHM     DetectLanguageReply_Language = 87
	DetectLanguageReply_KIK     DetectLanguageReply_Language = 88
	DetectLanguageReply_KIN     DetectLanguageReply_Language = 89
	DetectLanguageReply_KIR     DetectLanguageReply_Language = 90
	DetectLanguageReply_KOM     DetectLanguageReply_Language = 91
	DetectLanguageReply_KON     DetectLanguageReply_Language = 92
	DetectLanguageReply_KOR     DetectLanguageReply_Language = 93
	DetectLanguageReply_KUR     DetectLanguageReply_Language = 94
	DetectLanguageReply_KUA     DetectLanguageReply_Language = 95
	DetectLanguageReply_LAT     DetectLanguageReply_Language = 96
	DetectLanguageReply_LTZ     DetectLanguageReply_Language = 97
	DetectLanguageReply_LUG     DetectLanguageReply_Language = 98
	DetectLanguageReply_LIM     DetectLanguageReply_Language = 99
	DetectLanguageReply_LIN     DetectLanguageReply_Language = 100
	DetectLanguageReply_LAO     DetectLanguageReply_Language = 101
	DetectLanguageReply_LIT     DetectLanguageReply_Language = 102
	DetectLanguageReply_LUB     DetectLanguageReply_Language = 103
	DetectLanguageReply_LAV     DetectLanguageReply_Language = 104
	DetectLanguageReply_GLV     DetectLanguageReply_Language = 105
	DetectLanguageReply_MKD     DetectLanguageReply_Language = 106
	DetectLanguageReply_MLG     DetectLanguageReply_Language = 107
	DetectLanguageReply_MSA     DetectLanguageReply_Language = 108
	DetectLanguageReply_MAL     DetectLanguageReply_Language = 109
	DetectLanguageReply_MLT     DetectLanguageReply_Language = 110
	DetectLanguageReply_MRI     DetectLanguageReply_Language = 111
	DetectLanguageReply_MAR     DetectLanguageReply_Language = 112
	DetectLanguageReply_MAH     DetectLanguageReply_Language = 113
	DetectLanguageReply_MON     DetectLanguageReply_Language = 114
	DetectLanguageReply_NAU     DetectLanguageReply_Language = 115
	DetectLanguageReply_NAV     DetectLanguageReply_Language = 116
	DetectLanguageReply_NDE     DetectLanguageReply_Language = 117
	DetectLanguageReply_NSO     DetectLanguageReply_Language = 118
	DetectLanguageReply_NEP     DetectLanguageReply_Language = 119
	DetectLanguageReply_NDO     DetectLanguageReply_Language = 120
	DetectLanguageReply_NOR     DetectLanguageReply_Language = 121
	DetectLanguageReply_III     DetectLanguageReply_Language = 122
	DetectLanguageReply_NBL     DetectLanguageReply_Language = 123
	DetectLanguageReply_OCI     DetectLanguageReply_Language = 124
	DetectLanguageReply_OJI     DetectLanguageReply_Language = 125
	DetectLanguageReply_CHU     DetectLanguageReply_Language = 126
	DetectLanguageReply_ORM     DetectLanguageReply_Language = 127
	DetectLanguageReply_ORI     DetectLanguageReply_Language = 128
	DetectLanguageReply_OSS     DetectLanguageReply_Language = 129
	DetectLanguageReply_PAN     DetectLanguageReply_Language = 130
	DetectLanguageReply_PLI     DetectLanguageReply_Language = 131
	DetectLanguageReply_FAS     DetectLanguageReply_Language = 132
	DetectLanguageReply_POL     DetectLanguageReply_Language = 133
	DetectLanguageReply_PUS     DetectLanguageReply_Language = 134
	DetectLanguageReply_POR     DetectLanguageReply_Language = 135
	DetectLanguageReply_QUE     DetectLanguageReply_Language = 136
	DetectLanguageReply_ROH     DetectLanguageReply_Language = 137
	DetectLanguageReply_RUN     DetectLanguageReply_Language = 138
	DetectLanguageReply_RON     DetectLanguageReply_Language = 139
	DetectLanguageReply_RUS     DetectLanguageReply_Language = 140
	DetectLanguageReply_SAN     DetectLanguageReply_Language = 141
	DetectLanguageReply_SRD     DetectLanguageReply_Language = 142
	DetectLanguageReply_SND     DetectLanguageReply_Language = 143
	DetectLanguageReply_SMO     DetectLanguageReply_Language = 144
	DetectLanguageReply_SAG     DetectLanguageReply_Language = 145
	DetectLanguageReply_SRP     DetectLanguageReply_Language = 146
	DetectLanguageReply_GLA     DetectLanguageReply_Language = 147
	DetectLanguageReply_SNA     DetectLanguageReply_Language = 148
	DetectLanguageReply_SIN     DetectLanguageReply_Language = 149
	DetectLanguageReply_SLK     DetectLanguageReply_Language = 150
	DetectLanguageReply_SLV     DetectLanguageReply_Language = 151
	DetectLanguageReply_SOM     DetectLanguageReply_Language = 152
	DetectLanguageReply_SOT     DetectLanguageReply_Language = 153
	DetectLanguageReply_SPA     DetectLanguageReply_Language = 154
	DetectLanguageReply_SUN     DetectLanguageReply_Language = 155
	DetectLanguageReply_SWA     DetectLanguageReply_Language = 156
	DetectLanguageReply_SSW     DetectLanguageReply_Language = 157
	DetectLanguageReply_TAM     DetectLanguageReply_Language = 158
	DetectLanguageReply_TEL     DetectLanguageReply_Language = 159
	DetectLanguageReply_TGK     DetectLanguageReply_Language = 160
	DetectLanguageReply_THA     DetectLanguageReply_Language = 161
	DetectLanguageReply_TIR     DetectLanguageReply_Language = 162
	DetectLanguageReply_BOD     DetectLanguageReply_Language = 163
	DetectLanguageReply_TUK     DetectLanguageReply_Language = 164
	DetectLanguageReply_TGL     DetectLanguageReply_Language = 165
	DetectLanguageReply_FIL     DetectLanguageReply_Language = 166
	DetectLanguageReply_TSN     DetectLanguageReply_Language = 167
	DetectLanguageReply_TON     DetectLanguageReply_Language = 168
	DetectLanguageReply_TUR     DetectLanguageReply_Language = 169
	DetectLanguageReply_TSO     DetectLanguageReply_Language = 170
	DetectLanguageReply_TAT     DetectLanguageReply_Language = 171
	DetectLanguageReply_TWI     DetectLanguageReply_Language = 172
	DetectLanguageReply_TAH     DetectLanguageReply_Language = 173
	DetectLanguageReply_UIG     DetectLanguageReply_Language = 174
	DetectLanguageReply_UKR     DetectLanguageReply_Language = 175
	DetectLanguageReply_URD     DetectLanguageReply_Language = 176
	DetectLanguageReply_UZB     DetectLanguageReply_Language = 177
	DetectLanguageReply_VEN     DetectLanguageReply_Language = 178
	DetectLanguageReply_VIE     DetectLanguageReply_Language = 179
	DetectLanguageReply_VOL     DetectLanguageReply_Language = 180
	DetectLanguageReply_WLN     DetectLanguageReply_Language = 181
	DetectLanguageReply_CYM     DetectLanguageReply_Language = 182
	DetectLanguageReply_WOL     DetectLanguageReply_Language = 183
	DetectLanguageReply_FRY     DetectLanguageReply_Language = 184
	DetectLanguageReply_XHO     DetectLanguageReply_Language = 185
	DetectLanguageReply_YID     DetectLanguageReply_Language = 186
	DetectLanguageReply_YOR     DetectLanguageReply_Language = 187
	DetectLanguageReply_ZHA     DetectLanguageReply_Language = 188
	DetectLanguageReply_ZUL     DetectLanguageReply_Language = 189
	DetectLanguageReply_ACE     DetectLanguageReply_Language = 190
	DetectLanguageReply_ACH     DetectLanguageReply_Language = 191
	DetectLanguageReply_ADA     DetectLanguageReply_Language = 192
	DetectLanguageReply_ADY     DetectLanguageReply_Language = 193
	DetectLanguageReply_AFA     DetectLanguageReply_Language = 194
	DetectLanguageReply_AFH     DetectLanguageReply_Language = 195
	DetectLanguageReply_AIN     DetectLanguageReply_Language = 196
	DetectLanguageReply_AKK     DetectLanguageReply_Language = 197
	DetectLanguageReply_ALE     DetectLanguageReply_Language = 198
	DetectLanguageReply_ALG     DetectLanguageReply_Language = 199
	DetectLanguageReply_ALT     DetectLanguageReply_Language = 200
	DetectLanguageReply_ANG     DetectLanguageReply_Language = 201
	DetectLanguageReply_ANP     DetectLanguageReply_Language = 202
	DetectLanguageReply_APA     DetectLanguageReply_Language = 203
	DetectLanguageReply_ARC     DetectLanguageReply_Language = 204
	DetectLanguageReply_ARN     DetectLanguageReply_Language = 205
	DetectLanguageReply_ARP     DetectLanguageReply_Language = 206
	DetectLanguageReply_ART     DetectLanguageReply_Language = 207
	DetectLanguageReply_ARW     DetectLanguageReply_Language = 208
	DetectLanguageReply_AST     DetectLanguageReply_Language = 209
	DetectLanguageReply_ATH     DetectLanguageReply_Language = 210
	DetectLanguageReply_AUS     DetectLanguageReply_Language = 211
	DetectLanguageReply_AWA     DetectLanguageReply_Language = 212
	DetectLanguageReply_BAD     DetectLanguageReply_Language = 213
	DetectLanguageReply_BAI     DetectLanguageReply_Language = 214
	DetectLanguageReply_BAL     DetectLanguageReply_Language = 215
	DetectLanguageReply_BAN     DetectLanguageReply_Language = 216
	DetectLanguageReply_BAS     DetectLanguageReply_Language = 217
	DetectLanguageReply_BAT     DetectLanguageReply_Language = 218
	DetectLanguageReply_BEJ     DetectLanguageReply_Language = 219
	DetectLanguageReply_BEM     DetectLanguageReply_Language = 220
	DetectLanguageReply_BHO     DetectLanguageReply_Language = 221
	DetectLanguageReply_BIK     DetectLanguageReply_Language = 222
	DetectLanguageReply_BIN     DetectLanguageReply_Language = 223
	DetectLanguageReply_BLA     DetectLanguageReply_Language = 224
	DetectLanguageReply_BNT     DetectLanguageReply_Language = 225
	DetectLanguageReply_BRA     DetectLanguageReply_Language = 226
	DetectLanguageReply_BTK     DetectLanguageReply_Language = 227
	DetectLanguageReply_BUA     DetectLanguageReply_Language = 228
	DetectLanguageReply_BUG     DetectLanguageReply_Language = 229
	DetectLanguageReply_BYN     DetectLanguageReply_Language = 230
	DetectLanguageReply_CAD     DetectLanguageReply_Language = 231
	DetectLanguageReply_CAI     DetectLanguageReply_Language = 232
	DetectLanguageReply_CAR     DetectLanguageReply_Language = 233
	DetectLanguageReply_CAU     DetectLanguageReply_Language = 234
	DetectLanguageReply_CEB     DetectLanguageReply_Language = 235
	DetectLanguageReply_CEL     DetectLanguageReply_Language = 236
	DetectLanguageReply_CHB     DetectLanguageReply_Language = 237
	DetectLanguageReply_CHG     DetectLanguageReply_Language = 238
	DetectLanguageReply_CHK     DetectLanguageReply_Language = 239
	DetectLanguageReply_CHM     DetectLanguageReply_Language = 240
	DetectLanguageReply_CHN     DetectLanguageReply_Language = 241
	DetectLanguageReply_CHO     DetectLanguageReply_Language = 242
	DetectLanguageReply_CHP     DetectLanguageReply_Language = 243
	DetectLanguageReply_CHR     DetectLanguageReply_Language = 244
	DetectLanguageReply_CHY     DetectLanguageReply_Language = 245
	DetectLanguageReply_CMC     DetectLanguageReply_Language = 246
	DetectLanguageReply_COP     DetectLanguageReply_Language = 247
	DetectLanguageReply_CPE     DetectLanguageReply_Language = 248
	DetectLanguageReply_CPF     DetectLanguageReply_Language = 249
	DetectLanguageReply_CPP     DetectLanguageReply_Language = 250
	DetectLanguageReply_CRH     DetectLanguageReply_Language = 251
	DetectLanguageReply_CRP     DetectLanguageReply_Language = 252
	DetectLanguageReply_CSB     DetectLanguageReply_Language = 253
	DetectLanguageReply_CUS     DetectLanguageReply_Language = 254
	DetectLanguageReply_DAK     DetectLanguageReply_Language = 255
	DetectLanguageReply_DAR     DetectLanguageReply_Language = 256
	DetectLanguageReply_DAY     DetectLanguageReply_Language = 257
	DetectLanguageReply_DEL     DetectLanguageReply_Language = 258
	DetectLanguageReply_DEN     DetectLanguageReply_Language = 259
	DetectLanguageReply_DGR     DetectLanguageReply_Language = 260
	DetectLanguageReply_DIN     DetectLanguageReply_Language = 261
	DetectLanguageReply_DOI     DetectLanguageReply_Language = 262
	DetectLanguageReply_DRA     DetectLanguageReply_Language = 263
	DetectLanguageReply_DSB     DetectLanguageReply_Language = 264
	DetectLanguageReply_DUA     DetectLanguageReply_Language = 265
	DetectLanguageReply_DUM     DetectLanguageReply_Language = 266
	DetectLanguageReply_DYU     DetectLanguageReply_Language = 267
	DetectLanguageReply_EFI     DetectLanguageReply_Language = 268
	DetectLanguageReply_EGY     DetectLanguageReply_Language = 269
	DetectLanguageReply_EKA     DetectLanguageReply_Language = 270
	DetectLanguageReply_ELX     DetectLanguageReply_Language = 271
	DetectLanguageReply_ENM     DetectLanguageReply_Language = 272
	DetectLanguageReply_EWO     DetectLanguageReply_Language = 273
	DetectLanguageReply_FAN     DetectLanguageReply_Language = 274
	DetectLanguageReply_FAT     DetectLanguageReply_Language = 275
	DetectLanguageReply_FIU     DetectLanguageReply_Language = 276
	DetectLanguageReply_FON     DetectLanguageReply_Language = 277
	DetectLanguageReply_FRM     DetectLanguageReply_Language = 278
	DetectLanguageReply_FRO     DetectLanguageReply_Language = 279
	DetectLanguageReply_FRR     DetectLanguageReply_Language = 280
	DetectLanguageReply_FRS     DetectLanguageReply_Language = 281
	DetectLanguageReply_FUR     DetectLanguageReply_Language = 282
	DetectLanguageReply_GAA     DetectLanguageReply_Language = 283
	DetectLanguageReply_GAY     DetectLanguageReply_Language = 284
	DetectLanguageReply_GBA     DetectLanguageReply_Language = 285
	DetectLanguageReply_GEM     DetectLanguageReply_Language = 286
	DetectLanguageReply_GEZ     DetectLanguageReply_Language = 287
	DetectLanguageReply_GIL     DetectLanguageReply_Language = 288
	DetectLanguageReply_GMH     DetectLanguageReply_Language = 289
	DetectLanguageReply_GOH     DetectLanguageReply_Language = 290
	DetectLanguageReply_GON     DetectLanguageReply_Language = 291
	DetectLanguageReply_GOR     DetectLanguageReply_Language = 292
	DetectLanguageReply_GOT     DetectLanguageReply_Language = 293
	DetectLanguageReply_GRB     DetectLanguageReply_Language = 294
	DetectLanguageReply_GRC     DetectLanguageReply_Language = 295
	DetectLanguageReply_GSW     DetectLanguageReply_Language = 296
	DetectLanguageReply_GWI     DetectLanguageReply_Language = 297
	DetectLanguageReply_HAI     DetectLanguageReply_Language = 298
	DetectLanguageReply_HAW     DetectLanguageReply_Language = 299
	DetectLanguageReply_HIL     DetectLanguageReply_Language = 300
	DetectLanguageReply_HIM     DetectLanguageReply_Language = 301
	DetectLanguageReply_HIT     DetectLanguageReply_Language = 302
	DetectLanguageReply_HMN     DetectLanguageReply_Language = 303
	DetectLanguageReply_HSB     DetectLanguageReply_Language = 304
	DetectLanguageReply_HUP     DetectLanguageReply_Language = 305
	DetectLanguageReply_IBA     DetectLanguageReply_Language = 306
	DetectLanguageReply_IJO     DetectLanguageReply_Language = 307
	DetectLanguageReply_ILO     DetectLanguageReply_Language = 308
	DetectLanguageReply_INC     DetectLanguageReply_Language = 309
	DetectLanguageReply_INE     DetectLanguageReply_Language = 310
	DetectLanguageReply_INH     DetectLanguageReply_Language = 311
	DetectLanguageReply_IRA     DetectLanguageReply_Language = 312
	DetectLanguageReply_IRO     DetectLanguageReply_Language = 313
	DetectLanguageReply_JBO     DetectLanguageReply_Language = 314
	DetectLanguageReply_JPR     DetectLanguageReply_Language = 315
	DetectLanguageReply_JRB     DetectLanguageReply_Language = 316
	DetectLanguageReply_KAA     DetectLanguageReply_Language = 317
	DetectLanguageReply_KAB     DetectLanguageReply_Language = 318
	DetectLanguageReply_KAC     DetectLanguageReply_Language = 319
	DetectLanguageReply_KAM     DetectLanguageReply_Language = 320
	DetectLanguageReply_KAR     DetectLanguageReply_Language = 321
	DetectLanguageReply_KAW     DetectLanguageReply_Language = 322
	DetectLanguageReply_KBD     DetectLanguageReply_Language = 323
	DetectLanguageReply_KHA     DetectLanguageReply_Language = 324
	DetectLanguageReply_KHI     DetectLanguageReply_Language = 325
	DetectLanguageReply_KHO     DetectLanguageReply_Language = 326
	DetectLanguageReply_KMB     DetectLanguageReply_Language = 327
	DetectLanguageReply_KOK     DetectLanguageReply_Language = 328
	DetectLanguageReply_KOS     DetectLanguageReply_Language = 329
	DetectLanguageReply_KPE     DetectLanguageReply_Language = 330
	DetectLanguageReply_KRC     DetectLanguageReply_Language = 331
	DetectLanguageReply_KRL     DetectLanguageReply_Language = 332
	DetectLanguageReply_KRO     DetectLanguageReply_Language = 333
	DetectLanguageReply_KRU     DetectLanguageReply_Language = 334
	DetectLanguageReply_KUM     DetectLanguageReply_Language = 335
	DetectLanguageReply_KUT     DetectLanguageReply_Language = 336
	DetectLanguageReply_LAD     DetectLanguageReply_Language = 337
	DetectLanguageReply_LAH     DetectLanguageReply_Language = 338
	DetectLanguageReply_LAM     DetectLanguageReply_Language = 339
	DetectLanguageReply_LEZ     DetectLanguageReply_Language = 340
	DetectLanguageReply_LOL     DetectLanguageReply_Language = 341
	DetectLanguageReply_LOZ     DetectLanguageReply_Language = 342
	DetectLanguageReply_LUA     DetectLanguageReply_Language = 343
	DetectLanguageReply_LUI     DetectLanguageReply_Language = 344
	DetectLanguageReply_LUN     DetectLanguageReply_Language = 345
	DetectLanguageReply_LUO     DetectLanguageReply_Language = 346
	DetectLanguageReply_LUS     DetectLanguageReply_Language = 347
	DetectLanguageReply_MAD     DetectLanguageReply_Language = 348
	DetectLanguageReply_MAG     DetectLanguageReply_Language = 349
	DetectLanguageReply_MAI     DetectLanguageReply_Language = 350
	DetectLanguageReply_MAK     DetectLanguageReply_Language = 351
	DetectLanguageReply_MAN     DetectLanguageReply_Language = 352
	DetectLanguageReply_MAP     DetectLanguageReply_Language = 353
	DetectLanguageReply_MAS     DetectLanguageReply_Language = 354
	DetectLanguageReply_MDF     DetectLanguageReply_Language = 355
	DetectLanguageReply_MDR     DetectLanguageReply_Language = 356
	DetectLanguageReply_MEN     DetectLanguageReply_Language = 357
	DetectLanguageReply_MGA     DetectLanguageReply_Language = 358
	DetectLanguageReply_MIC     DetectLanguageReply_Language = 359
	DetectLanguageReply_MIN     DetectLanguageReply_Language = 360
	DetectLanguageReply_MIS     DetectLanguageReply_Language = 361
	DetectLanguageReply_MKH     DetectLanguageReply_Language = 362
	DetectLanguageReply_MNC     DetectLanguageReply_Language = 363
	DetectLanguageReply_MNI     DetectLanguageReply_Language = 364
	DetectLanguageReply_MNO     DetectLanguageReply_Language = 365
	DetectLanguageReply_MOH     DetectLanguageReply_Language = 366
	DetectLanguageReply_MOS     DetectLanguageReply_Language = 367
	DetectLanguageReply_MUL     DetectLanguageReply_Language = 368
	DetectLanguageReply_MUN     DetectLanguageReply_Language = 369
	DetectLanguageReply_MUS     DetectLanguageReply_Language = 370
	DetectLanguageReply_MWL     DetectLanguageReply_Language = 371
	DetectLanguageReply_MWR     DetectLanguageReply_Language = 372
	DetectLanguageReply_MYN     DetectLanguageReply_Language = 373
	DetectLanguageReply_MYV     DetectLanguageReply_Language = 374
	DetectLanguageReply_NAH     DetectLanguageReply_Language = 375
	DetectLanguageReply_NAI     DetectLanguageReply_Language = 376
	DetectLanguageReply_NAP     DetectLanguageReply_Language = 377
	DetectLanguageReply_NDS     DetectLanguageReply_Language = 378
	DetectLanguageReply_NEW     DetectLanguageReply_Language = 379
	DetectLanguageReply_NIA     DetectLanguageReply_Language = 380
	DetectLanguageReply_NIC     DetectLanguageReply_Language = 381
	DetectLanguageReply_NIU     DetectLanguageReply_Language = 382
	DetectLanguageReply_NOG     DetectLanguageReply_Language = 383
	DetectLanguageReply_NON     DetectLanguageReply_Language = 384
	DetectLanguageReply_NQO     DetectLanguageReply_Language = 385
	DetectLanguageReply_NUB     DetectLanguageReply_Language = 386
	DetectLanguageReply_NWC     DetectLanguageReply_Language = 387
	DetectLanguageReply_NYM     DetectLanguageReply_Language = 388
	DetectLanguageReply_NYN     DetectLanguageReply_Language = 389
	DetectLanguageReply_NYO     DetectLanguageReply_Language = 390
	DetectLanguageReply_NZI     DetectLanguageReply_Language = 391
	DetectLanguageReply_OSA     DetectLanguageReply_Language = 392
	DetectLanguageReply_OTA     DetectLanguageReply_Language = 393
	DetectLanguageReply_OTO     DetectLanguageReply_Language = 394
	DetectLanguageReply_PAA     DetectLanguageReply_Language = 395
	DetectLanguageReply_PAG     DetectLanguageReply_Language = 396
	DetectLanguageReply_PAL     DetectLanguageReply_Language = 397
	DetectLanguageReply_PAM     DetectLanguageReply_Language = 398
	DetectLanguageReply_PAP     DetectLanguageReply_Language = 399
	DetectLanguageReply_PAU     DetectLanguageReply_Language = 400
	DetectLanguageReply_PEO     DetectLanguageReply_Language = 401
	DetectLanguageReply_PHI     DetectLanguageReply_Language = 402
	DetectLanguageReply_PHN     DetectLanguageReply_Language = 403
	DetectLanguageReply_PON     DetectLanguageReply_Language = 404
	DetectLanguageReply_PRA     DetectLanguageReply_Language = 405
	DetectLanguageReply_PRO     DetectLanguageReply_Language = 406
	DetectLanguageReply_RAJ     DetectLanguageReply_Language = 407
	DetectLanguageReply_RAP     DetectLanguageReply_Language = 408
	DetectLanguageReply_RAR     DetectLanguageReply_Language = 409
	DetectLanguageReply_ROA     DetectLanguageReply_Language = 410
	DetectLanguageReply_ROM     DetectLanguageReply_Language = 411
	DetectLanguageReply_RUP     DetectLanguageReply_Language = 412
	DetectLanguageReply_SAD     DetectLanguageReply_Language = 413
	DetectLanguageReply_SAH     DetectLanguageReply_Language = 414
	DetectLanguageReply_SAI     DetectLanguageReply_Language = 415
	DetectLanguageReply_SAL     DetectLanguageReply_Language = 416
	DetectLanguageReply_SAM     DetectLanguageReply_Language = 417
	DetectLanguageReply_SAS     DetectLanguageReply_Language = 418
	DetectLanguageReply_SAT     DetectLanguageReply_Language = 419
	DetectLanguageReply_SCN     DetectLanguageReply_Language = 420
	DetectLanguageReply_SCO     DetectLanguageReply_Language = 421
	DetectLanguageReply_SEL     DetectLanguageReply_Language = 422
	DetectLanguageReply_SEM     DetectLanguageReply_Language = 423
	DetectLanguageReply_SGA     DetectLanguageReply_Language = 424
	DetectLanguageReply_SGN     DetectLanguageReply_Language = 425
	DetectLanguageReply_SHN     DetectLanguageReply_Language = 426
	DetectLanguageReply_SID     DetectLanguageReply_Language = 427
	DetectLanguageReply_SIO     DetectLanguageReply_Language = 428
	DetectLanguageReply_SIT     DetectLanguageReply_Language = 429
	DetectLanguageReply_SLA     DetectLanguageReply_Language = 430
	DetectLanguageReply_SMI     DetectLanguageReply_Language = 431
	DetectLanguageReply_SMN     DetectLanguageReply_Language = 432
	DetectLanguageReply_SMS     DetectLanguageReply_Language = 433
	DetectLanguageReply_SNK     DetectLanguageReply_Language = 434
	DetectLanguageReply_SOG     DetectLanguageReply_Language = 435
	DetectLanguageReply_SON     DetectLanguageReply_Language = 436
	DetectLanguageReply_SRN     DetectLanguageReply_Language = 437
	DetectLanguageReply_SRR     DetectLanguageReply_Language = 438
	DetectLanguageReply_SSA     DetectLanguageReply_Language = 439
	DetectLanguageReply_SUK     DetectLanguageReply_Language = 440
	DetectLanguageReply_SUS     DetectLanguageReply_Language = 441
	DetectLanguageReply_SUX     DetectLanguageReply_Language = 442
	DetectLanguageReply_SYC     DetectLanguageReply_Language = 443
	DetectLanguageReply_SYR     DetectLanguageReply_Language = 444
	DetectLanguageReply_TAI     DetectLanguageReply_Language = 445
	DetectLanguageReply_TEM     DetectLanguageReply_Language = 446
	DetectLanguageReply_TER     DetectLanguageReply_Language = 447
	DetectLanguageReply_TET     DetectLanguageReply_Language = 448
	DetectLanguageReply_TIG     DetectLanguageReply_Language = 449
	DetectLanguageReply_TIV     DetectLanguageReply_Language = 450
	DetectLanguageReply_TKL     DetectLanguageReply_Language = 451
	DetectLanguageReply_TLH     DetectLanguageReply_Language = 452
	DetectLanguageReply_TLI     DetectLanguageReply_Language = 453
	DetectLanguageReply_TMH     DetectLanguageReply_Language = 454
	DetectLanguageReply_TOG     DetectLanguageReply_Language = 455
	DetectLanguageReply_TPI     DetectLanguageReply_Language = 456
	DetectLanguageReply_TSI     DetectLanguageReply_Language = 457
	DetectLanguageReply_TUM     DetectLanguageReply_Language = 458
	DetectLanguageReply_TUP     DetectLanguageReply_Language = 459
	DetectLanguageReply_TUT     DetectLanguageReply_Language = 460
	DetectLanguageReply_TVL     DetectLanguageReply_Language = 461
	DetectLanguageReply_TYV     DetectLanguageReply_Language = 462
	DetectLanguageReply_UDM     DetectLanguageReply_Language = 463
	DetectLanguageReply_UGA     DetectLanguageReply_Language = 464
	DetectLanguageReply_UMB     DetectLanguageReply_Language = 465
	DetectLanguageReply_UND     DetectLanguageReply_Language = 466
	DetectLanguageReply_VAI     DetectLanguageReply_Language = 467
	DetectLanguageReply_VOT     DetectLanguageReply_Language = 468
	DetectLanguageReply_WAK     DetectLanguageReply_Language = 469
	DetectLanguageReply_WAL     DetectLanguageReply_Language = 470
	DetectLanguageReply_WAR     DetectLanguageReply_Language = 471
	DetectLanguageReply_WAS     DetectLanguageReply_Language = 472
	DetectLanguageReply_WEN     DetectLanguageReply_Language = 473
	DetectLanguageReply_XAL     DetectLanguageReply_Language = 474
	DetectLanguageReply_YAO     DetectLanguageReply_Language = 475
	DetectLanguageReply_YAP     DetectLanguageReply_Language = 476
	DetectLanguageReply_YPK     DetectLanguageReply_Language = 477
	DetectLanguageReply_ZAP     DetectLanguageReply_Language = 478
	DetectLanguageReply_ZBL     DetectLanguageReply_Language = 479
	DetectLanguageReply_ZEN     DetectLanguageReply_Language = 480
	DetectLanguageReply_ZGH     DetectLanguageReply_Language = 481
	DetectLanguageReply_ZND     DetectLanguageReply_Language = 482
	DetectLanguageReply_ZUN     DetectLanguageReply_Language = 483
	DetectLanguageReply_ZXX     DetectLanguageReply_Language = 484
	DetectLanguageReply_ZZA     DetectLanguageReply_Language = 485
)

var DetectLanguageReply_Language_name = map[int32]string{
	0:   "UNKNOWN",
	1:   "NOB",
	2:   "NNO",
	3:   "DAN",
	4:   "SWE",
	5:   "ENG",
	6:   "FRA",
	7:   "SMA",
	8:   "SMJ",
	9:   "SME",
	10:  "ABK",
	11:  "AAR",
	12:  "AFR",
	13:  "AKA",
	14:  "SQI",
	15:  "AMH",
	16:  "ARA",
	17:  "ARG",
	18:  "HYE",
	19:  "ASM",
	20:  "AVA",
	21:  "AVE",
	22:  "AYM",
	23:  "AZE",
	24:  "BAM",
	25:  "BAK",
	26:  "EUS",
	27:  "BEL",
	28:  "BEN",
	29:  "BER",
	30:  "BIS",
	31:  "BOS",
	32:  "BRE",
	33:  "BUL",
	34:  "MYA",
	35:  "CAT",
	36:  "CHA",
	37:  "CHE",
	38:  "NYA",
	39:  "ZHO",
	40:  "CHV",
	41:  "COR",
	42:  "COS",
	43:  "CRE",
	44:  "HRV",
	45:  "CES",
	46:  "PRS",
	47:  "DIV",
	48:  "NLD",
	49:  "DZO",
	50:  "EPO",
	51:  "EST",
	52:  "EWE",
	53:  "FAO",
	54:  "FIJ",
	55:  "FIN",
	56:  "FUL",
	57:  "GLG",
	58:  "KAT",
	59:  "DEU",
	60:  "ELL",
	61:  "GRN",
	62:  "GUJ",
	63:  "HAT",
	64:  "HAU",
	65:  "HEB",
	66:  "HER",
	67:  "HIN",
	68:  "HMO",
	69:  "HUN",
	70:  "INA",
	71:  "IND",
	72:  "ILE",
	73:  "GLE",
	74:  "IBO",
	75:  "IPK",
	76:  "IDO",
	77:  "ISL",
	78:  "ITA",
	79:  "IKU",
	80:  "JPN",
	81:  "JAV",
	82:  "KAL",
	83:  "KAN",
	84:  "KAU",
	85:  "KAS",
	86:  "KAZ",
	87:  "KHM",
	88:  "KIK",
	89:  "KIN",
	90:  "KIR",
	91:  "KOM",
	92:  "KON",
	93:  "KOR",
	94:  "KUR",
	95:  "KUA",
	96:  "LAT",
	97:  "LTZ",
	98:  "LUG",
	99:  "LIM",
	100: "LIN",
	101: "LAO",
	102: "LIT",
	103: "LUB",
	104: "LAV",
	105: "GLV",
	106: "MKD",
	107: "MLG",
	108: "MSA",
	109: "MAL",
	110: "MLT",
	111: "MRI",
	112: "MAR",
	113: "MAH",
	114: "MON",
	115: "NAU",
	116: "NAV",
	117: "NDE",
	118: "NSO",
	119: "NEP",
	120: "NDO",
	121: "NOR",
	122: "III",
	123: "NBL",
	124: "OCI",
	125: "OJI",
	126: "CHU",
	127: "ORM",
	128: "ORI",
	129: "OSS",
	130: "PAN",
	131: "PLI",
	132: "FAS",
	133: "POL",
	134: "PUS",
	135: "POR",
	136: "QUE",
	137: "ROH",
	138: "RUN",
	139: "RON",
	140: "RUS",
	141: "SAN",
	142: "SRD",
	143: "SND",
	144: "SMO",
	145: "SAG",
	146: "SRP",
	147: "GLA",
	148: "SNA",
	149: "SIN",
	150: "SLK",
	151: "SLV",
	152: "SOM",
	153: "SOT",
	154: "SPA",
	155: "SUN",
	156: "SWA",
	157: "SSW",
	158: "TAM",
	159: "TEL",
	160: "TGK",
	161: "THA",
	162: "TIR",
	163: "BOD",
	164: "TUK",
	165: "TGL",
	166: "FIL",
	167: "TSN",
	168: "TON",
	169: "TUR",
	170: "TSO",
	171: "TAT",
	172: "TWI",
	173: "TAH",
	174: "UIG",
	175: "UKR",
	176: "URD",
	177: "UZB",
	178: "VEN",
	179: "VIE",
	180: "VOL",
	181: "WLN",
	182: "CYM",
	183: "WOL",
	184: "FRY",
	185: "XHO",
	186: "YID",
	187: "YOR",
	188: "ZHA",
	189: "ZUL",
	190: "ACE",
	191: "ACH",
	192: "ADA",
	193: "ADY",
	194: "AFA",
	195: "AFH",
	196: "AIN",
	197: "AKK",
	198: "ALE",
	199: "ALG",
	200: "ALT",
	201: "ANG",
	202: "ANP",
	203: "APA",
	204: "ARC",
	205: "ARN",
	206: "ARP",
	207: "ART",
	208: "ARW",
	209: "AST",
	210: "ATH",
	211: "AUS",
	212: "AWA",
	213: "BAD",
	214: "BAI",
	215: "BAL",
	216: "BAN",
	217: "BAS",
	218: "BAT",
	219: "BEJ",
	220: "BEM",
	221: "BHO",
	222: "BIK",
	223: "BIN",
	224: "BLA",
	225: "BNT",
	226: "BRA",
	227: "BTK",
	228: "BUA",
	229: "BUG",
	230: "BYN",
	231: "CAD",
	232: "CAI",
	233: "CAR",
	234: "CAU",
	235: "CEB",
	236: "CEL",
	237: "CHB",
	238: "CHG",
	239: "CHK",
	240: "CHM",
	241: "CHN",
	242: "CHO",
	243: "CHP",
	244: "CHR",
	245: "CHY",
	246: "CMC",
	247: "COP",
	248: "CPE",
	249: "CPF",
	250: "CPP",
	251: "CRH",
	252: "CRP",
	253: "CSB",
	254: "CUS",
	255: "DAK",
	256: "DAR",
	257: "DAY",
	258: "DEL",
	259: "DEN",
	260: "DGR",
	261: "DIN",
	262: "DOI",
	263: "DRA",
	264: "DSB",
	265: "DUA",
	266: "DUM",
	267: "DYU",
	268: "EFI",
	269: "EGY",
	270: "EKA",
	271: "ELX",
	272: "ENM",
	273: "EWO",
	274: "FAN",
	275: "FAT",
	276: "FIU",
	277: "FON",
	278: "FRM",
	279: "FRO",
	280: "FRR",
	281: "FRS",
	282: "FUR",
	283: "GAA",
	284: "GAY",
	285: "GBA",
	286: "GEM",
	287: "GEZ",
	288: "GIL",
	289: "GMH",
	290: "GOH",
	291: "GON",
	292: "GOR",
	293: "GOT",
	294: "GRB",
	295: "GRC",
	296: "GSW",
	297: "GWI",
	298: "HAI",
	299: "HAW",
	300: "HIL",
	301: "HIM",
	302: "HIT",
	303: "HMN",
	304: "HSB",
	305: "HUP",
	306: "IBA",
	307: "IJO",
	308: "ILO",
	309: "INC",
	310: "INE",
	311: "INH",
	312: "IRA",
	313: "IRO",
	314: "JBO",
	315: "JPR",
	316: "JRB",
	317: "KAA",
	318: "KAB",
	319: "KAC",
	320: "KAM",
	321: "KAR",
	322: "KAW",
	323: "KBD",
	324: "KHA",
	325: "KHI",
	326: "KHO",
	327: "KMB",
	328: "KOK",
	329: "KOS",
	330: "KPE",
	331: "KRC",
	332: "KRL",
	333: "KRO",
	334: "KRU",
	335: "KUM",
	336: "KUT",
	337: "LAD",
	338: "LAH",
	339: "LAM",
	340: "LEZ",
	341: "LOL",
	342: "LOZ",
	343: "LUA",
	344: "LUI",
	345: "LUN",
	346: "LUO",
	347: "LUS",
	348: "MAD",
	349: "MAG",
	350: "MAI",
	351: "MAK",
	352: "MAN",
	353: "MAP",
	354: "MAS",
	355: "MDF",
	356: "MDR",
	357: "MEN",
	358: "MGA",
	359: "MIC",
	360: "MIN",
	361: "MIS",
	362: "MKH",
	363: "MNC",
	364: "MNI",
	365: "MNO",
	366: "MOH",
	367: "MOS",
	368: "MUL",
	369: "MUN",
	370: "MUS",
	371: "MWL",
	372: "MWR",
	373: "MYN",
	374: "MYV",
	375: "NAH",
	376: "NAI",
	377: "NAP",
	378: "NDS",
	379: "NEW",
	380: "NIA",
	381: "NIC",
	382: "NIU",
	383: "NOG",
	384: "NON",
	385: "NQO",
	386: "NUB",
	387: "NWC",
	388: "NYM",
	389: "NYN",
	390: "NYO",
	391: "NZI",
	392: "OSA",
	393: "OTA",
	394: "OTO",
	395: "PAA",
	396: "PAG",
	397: "PAL",
	398: "PAM",
	399: "PAP",
	400: "PAU",
	401: "PEO",
	402: "PHI",
	403: "PHN",
	404: "PON",
	405: "PRA",
	406: "PRO",
	407: "RAJ",
	408: "RAP",
	409: "RAR",
	410: "ROA",
	411: "ROM",
	412: "RUP",
	413: "SAD",
	414: "SAH",
	415: "SAI",
	416: "SAL",
	417: "SAM",
	418: "SAS",
	419: "SAT",
	420: "SCN",
	421: "SCO",
	422: "SEL",
	423: "SEM",
	424: "SGA",
	425: "SGN",
	426: "SHN",
	427: "SID",
	428: "SIO",
	429: "SIT",
	430: "SLA",
	431: "SMI",
	432: "SMN",
	433: "SMS",
	434: "SNK",
	435: "SOG",
	436: "SON",
	437: "SRN",
	438: "SRR",
	439: "SSA",
	440: "SUK",
	441: "SUS",
	442: "SUX",
	443: "SYC",
	444: "SYR",
	445: "TAI",
	446: "TEM",
	447: "TER",
	448: "TET",
	449: "TIG",
	450: "TIV",
	451: "TKL",
	452: "TLH",
	453: "TLI",
	454: "TMH",
	455: "TOG",
	456: "TPI",
	457: "TSI",
	458: "TUM",
	459: "TUP",
	460: "TUT",
	461: "TVL",
	462: "TYV",
	463: "UDM",
	464: "UGA",
	465: "UMB",
	466: "UND",
	467: "VAI",
	468: "VOT",
	469: "WAK",
	470: "WAL",
	471: "WAR",
	472: "WAS",
	473: "WEN",
	474: "XAL",
	475: "YAO",
	476: "YAP",
	477: "YPK",
	478: "ZAP",
	479: "ZBL",
	480: "ZEN",
	481: "ZGH",
	482: "ZND",
	483: "ZUN",
	484: "ZXX",
	485: "ZZA",
}
var DetectLanguageReply_Language_value = map[string]int32{
	"UNKNOWN": 0,
	"NOB":     1,
	"NNO":     2,
	"DAN":     3,
	"SWE":     4,
	"ENG":     5,
	"FRA":     6,
	"SMA":     7,
	"SMJ":     8,
	"SME":     9,
	"ABK":     10,
	"AAR":     11,
	"AFR":     12,
	"AKA":     13,
	"SQI":     14,
	"AMH":     15,
	"ARA":     16,
	"ARG":     17,
	"HYE":     18,
	"ASM":     19,
	"AVA":     20,
	"AVE":     21,
	"AYM":     22,
	"AZE":     23,
	"BAM":     24,
	"BAK":     25,
	"EUS":     26,
	"BEL":     27,
	"BEN":     28,
	"BER":     29,
	"BIS":     30,
	"BOS":     31,
	"BRE":     32,
	"BUL":     33,
	"MYA":     34,
	"CAT":     35,
	"CHA":     36,
	"CHE":     37,
	"NYA":     38,
	"ZHO":     39,
	"CHV":     40,
	"COR":     41,
	"COS":     42,
	"CRE":     43,
	"HRV":     44,
	"CES":     45,
	"PRS":     46,
	"DIV":     47,
	"NLD":     48,
	"DZO":     49,
	"EPO":     50,
	"EST":     51,
	"EWE":     52,
	"FAO":     53,
	"FIJ":     54,
	"FIN":     55,
	"FUL":     56,
	"GLG":     57,
	"KAT":     58,
	"DEU":     59,
	"ELL":     60,
	"GRN":     61,
	"GUJ":     62,
	"HAT":     63,
	"HAU":     64,
	"HEB":     65,
	"HER":     66,
	"HIN":     67,
	"HMO":     68,
	"HUN":     69,
	"INA":     70,
	"IND":     71,
	"ILE":     72,
	"GLE":     73,
	"IBO":     74,
	"IPK":     75,
	"IDO":     76,
	"ISL":     77,
	"ITA":     78,
	"IKU":     79,
	"JPN":     80,
	"JAV":     81,
	"KAL":     82,
	"KAN":     83,
	"KAU":     84,
	"KAS":     85,
	"KAZ":     86,
	"KHM":     87,
	"KIK":     88,
	"KIN":     89,
	"KIR":     90,
	"KOM":     91,
	"KON":     92,
	"KOR":     93,
	"KUR":     94,
	"KUA":     95,
	"LAT":     96,
	"LTZ":     97,
	"LUG":     98,
	"LIM":     99,
	"LIN":     100,
	"LAO":     101,
	"LIT":     102,
	"LUB":     103,
	"LAV":     104,
	"GLV":     105,
	"MKD":     106,
	"MLG":     107,
	"MSA":     108,
	"MAL":     109,
	"MLT":     110,
	"MRI":     111,
	"MAR":     112,
	"MAH":     113,
	"MON":     114,
	"NAU":     115,
	"NAV":     116,
	"NDE":     117,
	"NSO":     118,
	"NEP":     119,
	"NDO":     120,
	"NOR":     121,
	"III":     122,
	"NBL":     123,
	"OCI":     124,
	"OJI":     125,
	"CHU":     126,
	"ORM":     127,
	"ORI":     128,
	"OSS":     129,
	"PAN":     130,
	"PLI":     131,
	"FAS":     132,
	"POL":     133,
	"PUS":     134,
	"POR":     135,
	"QUE":     136,
	"ROH":     137,
	"RUN":     138,
	"RON":     139,
	"RUS":     140,
	"SAN":     141,
	"SRD":     142,
	"SND":     143,
	"SMO":     144,
	"SAG":     145,
	"SRP":     146,
	"GLA":     147,
	"SNA":     148,
	"SIN":     149,
	"SLK":     150,
	"SLV":     151,
	"SOM":     152,
	"SOT":     153,
	"SPA":     154,
	"SUN":     155,
	"SWA":     156,
	"SSW":     157,
	"TAM":     158,
	"TEL":     159,
	"TGK":     160,
	"THA":     161,
	"TIR":     162,
	"BOD":     163,
	"TUK":     164,
	"TGL":     165,
	"FIL":     166,
	"TSN":     167,
	"TON":     168,
	"TUR":     169,
	"TSO":     170,
	"TAT":     171,
	"TWI":     172,
	"TAH":     173,
	"UIG":     174,
	"UKR":     175,
	"URD":     176,
	"UZB":     177,
	"VEN":     178,
	"VIE":     179,
	"VOL":     180,
	"WLN":     181,
	"CYM":     182,
	"WOL":     183,
	"FRY":     184,
	"XHO":     185,
	"YID":     186,
	"YOR":     187,
	"ZHA":     188,
	"ZUL":     189,
	"ACE":     190,
	"ACH":     191,
	"ADA":     192,
	"ADY":     193,
	"AFA":     194,
	"AFH":     195,
	"AIN":     196,
	"AKK":     197,
	"ALE":     198,
	"ALG":     199,
	"ALT":     200,
	"ANG":     201,
	"ANP":     202,
	"APA":     203,
	"ARC":     204,
	"ARN":     205,
	"ARP":     206,
	"ART":     207,
	"ARW":     208,
	"AST":     209,
	"ATH":     210,
	"AUS":     211,
	"AWA":     212,
	"BAD":     213,
	"BAI":     214,
	"BAL":     215,
	"BAN":     216,
	"BAS":     217,
	"BAT":     218,
	"BEJ":     219,
	"BEM":     220,
	"BHO":     221,
	"BIK":     222,
	"BIN":     223,
	"BLA":     224,
	"BNT":     225,
	"BRA":     226,
	"BTK":     227,
	"BUA":     228,
	"BUG":     229,
	"BYN":     230,
	"CAD":     231,
	"CAI":     232,
	"CAR":     233,
	"CAU":     234,
	"CEB":     235,
	"CEL":     236,
	"CHB":     237,
	"CHG":     238,
	"CHK":     239,
	"CHM":     240,
	"CHN":     241,
	"CHO":     242,
	"CHP":     243,
	"CHR":     244,
	"CHY":     245,
	"CMC":     246,
	"COP":     247,
	"CPE":     248,
	"CPF":     249,
	"CPP":     250,
	"CRH":     251,
	"CRP":     252,
	"CSB":     253,
	"CUS":     254,
	"DAK":     255,
	"DAR":     256,
	"DAY":     257,
	"DEL":     258,
	"DEN":     259,
	"DGR":     260,
	"DIN":     261,
	"DOI":     262,
	"DRA":     263,
	"DSB":     264,
	"DUA":     265,
	"DUM":     266,
	"DYU":     267,
	"EFI":     268,
	"EGY":     269,
	"EKA":     270,
	"ELX":     271,
	"ENM":     272,
	"EWO":     273,
	"FAN":     274,
	"FAT":     275,
	"FIU":     276,
	"FON":     277,
	"FRM":     278,
	"FRO":     279,
	"FRR":     280,
	"FRS":     281,
	"FUR":     282,
	"GAA":     283,
	"GAY":     284,
	"GBA":     285,
	"GEM":     286,
	"GEZ":     287,
	"GIL":     288,
	"GMH":     289,
	"GOH":     290,
	"GON":     291,
	"GOR":     292,
	"GOT":     293,
	"GRB":     294,
	"GRC":     295,
	"GSW":     296,
	"GWI":     297,
	"HAI":     298,
	"HAW":     299,
	"HIL":     300,
	"HIM":     301,
	"HIT":     302,
	"HMN":     303,
	"HSB":     304,
	"HUP":     305,
	"IBA":     306,
	"IJO":     307,
	"ILO":     308,
	"INC":     309,
	"INE":     310,
	"INH":     311,
	"IRA":     312,
	"IRO":     313,
	"JBO":     314,
	"JPR":     315,
	"JRB":     316,
	"KAA":     317,
	"KAB":     318,
	"KAC":     319,
	"KAM":     320,
	"KAR":     321,
	"KAW":     322,
	"KBD":     323,
	"KHA":     324,
	"KHI":     325,
	"KHO":     326,
	"KMB":     327,
	"KOK":     328,
	"KOS":     329,
	"KPE":     330,
	"KRC":     331,
	"KRL":     332,
	"KRO":     333,
	"KRU":     334,
	"KUM":     335,
	"KUT":     336,
	"LAD":     337,
	"LAH":     338,
	"LAM":     339,
	"LEZ":     340,
	"LOL":     341,
	"LOZ":     342,
	"LUA":     343,
	"LUI":     344,
	"LUN":     345,
	"LUO":     346,
	"LUS":     347,
	"MAD":     348,
	"MAG":     349,
	"MAI":     350,
	"MAK":     351,
	"MAN":     352,
	"MAP":     353,
	"MAS":     354,
	"MDF":     355,
	"MDR":     356,
	"MEN":     357,
	"MGA":     358,
	"MIC":     359,
	"MIN":     360,
	"MIS":     361,
	"MKH":     362,
	"MNC":     363,
	"MNI":     364,
	"MNO":     365,
	"MOH":     366,
	"MOS":     367,
	"MUL":     368,
	"MUN":     369,
	"MUS":     370,
	"MWL":     371,
	"MWR":     372,
	"MYN":     373,
	"MYV":     374,
	"NAH":     375,
	"NAI":     376,
	"NAP":     377,
	"NDS":     378,
	"NEW":     379,
	"NIA":     380,
	"NIC":     381,
	"NIU":     382,
	"NOG":     383,
	"NON":     384,
	"NQO":     385,
	"NUB":     386,
	"NWC":     387,
	"NYM":     388,
	"NYN":     389,
	"NYO":     390,
	"NZI":     391,
	"OSA":     392,
	"OTA":     393,
	"OTO":     394,
	"PAA":     395,
	"PAG":     396,
	"PAL":     397,
	"PAM":     398,
	"PAP":     399,
	"PAU":     400,
	"PEO":     401,
	"PHI":     402,
	"PHN":     403,
	"PON":     404,
	"PRA":     405,
	"PRO":     406,
	"RAJ":     407,
	"RAP":     408,
	"RAR":     409,
	"ROA":     410,
	"ROM":     411,
	"RUP":     412,
	"SAD":     413,
	"SAH":     414,
	"SAI":     415,
	"SAL":     416,
	"SAM":     417,
	"SAS":     418,
	"SAT":     419,
	"SCN":     420,
	"SCO":     421,
	"SEL":     422,
	"SEM":     423,
	"SGA":     424,
	"SGN":     425,
	"SHN":     426,
	"SID":     427,
	"SIO":     428,
	"SIT":     429,
	"SLA":     430,
	"SMI":     431,
	"SMN":     432,
	"SMS":     433,
	"SNK":     434,
	"SOG":     435,
	"SON":     436,
	"SRN":     437,
	"SRR":     438,
	"SSA":     439,
	"SUK":     440,
	"SUS":     441,
	"SUX":     442,
	"SYC":     443,
	"SYR":     444,
	"TAI":     445,
	"TEM":     446,
	"TER":     447,
	"TET":     448,
	"TIG":     449,
	"TIV":     450,
	"TKL":     451,
	"TLH":     452,
	"TLI":     453,
	"TMH":     454,
	"TOG":     455,
	"TPI":     456,
	"TSI":     457,
	"TUM":     458,
	"TUP":     459,
	"TUT":     460,
	"TVL":     461,
	"TYV":     462,
	"UDM":     463,
	"UGA":     464,
	"UMB":     465,
	"UND":     466,
	"VAI":     467,
	"VOT":     468,
	"WAK":     469,
	"WAL":     470,
	"WAR":     471,
	"WAS":     472,
	"WEN":     473,
	"XAL":     474,
	"YAO":     475,
	"YAP":     476,
	"YPK":     477,
	"ZAP":     478,
	"ZBL":     479,
	"ZEN":     480,
	"ZGH":     481,
	"ZND":     482,
	"ZUN":     483,
	"ZXX":     484,
	"ZZA":     485,
}

func (x DetectLanguageReply_Language) String() string {
	return proto.EnumName(DetectLanguageReply_Language_name, int32(x))
}
func (DetectLanguageReply_Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

// Request message for `Maalfrid.DetectLanguage`
type DetectLanguageRequest struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *DetectLanguageRequest) Reset()                    { *m = DetectLanguageRequest{} }
func (m *DetectLanguageRequest) String() string            { return proto.CompactTextString(m) }
func (*DetectLanguageRequest) ProtoMessage()               {}
func (*DetectLanguageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DetectLanguageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// Reply message for `Maalfrid.DetectLanguage`
type DetectLanguageReply struct {
	// The detected language
	Language DetectLanguageReply_Language `protobuf:"varint,1,opt,name=language,enum=maalfrid.DetectLanguageReply_Language" json:"language,omitempty"`
}

func (m *DetectLanguageReply) Reset()                    { *m = DetectLanguageReply{} }
func (m *DetectLanguageReply) String() string            { return proto.CompactTextString(m) }
func (*DetectLanguageReply) ProtoMessage()               {}
func (*DetectLanguageReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DetectLanguageReply) GetLanguage() DetectLanguageReply_Language {
	if m != nil {
		return m.Language
	}
	return DetectLanguageReply_UNKNOWN
}

func init() {
	proto.RegisterType((*DetectLanguageRequest)(nil), "maalfrid.DetectLanguageRequest")
	proto.RegisterType((*DetectLanguageReply)(nil), "maalfrid.DetectLanguageReply")
	proto.RegisterEnum("maalfrid.DetectLanguageReply_Language", DetectLanguageReply_Language_name, DetectLanguageReply_Language_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Maalfrid service

type MaalfridClient interface {
	DetectLanguage(ctx context.Context, in *DetectLanguageRequest, opts ...grpc.CallOption) (*DetectLanguageReply, error)
}

type maalfridClient struct {
	cc *grpc.ClientConn
}

func NewMaalfridClient(cc *grpc.ClientConn) MaalfridClient {
	return &maalfridClient{cc}
}

func (c *maalfridClient) DetectLanguage(ctx context.Context, in *DetectLanguageRequest, opts ...grpc.CallOption) (*DetectLanguageReply, error) {
	out := new(DetectLanguageReply)
	err := grpc.Invoke(ctx, "/maalfrid.Maalfrid/DetectLanguage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Maalfrid service

type MaalfridServer interface {
	DetectLanguage(context.Context, *DetectLanguageRequest) (*DetectLanguageReply, error)
}

func RegisterMaalfridServer(s *grpc.Server, srv MaalfridServer) {
	s.RegisterService(&_Maalfrid_serviceDesc, srv)
}

func _Maalfrid_DetectLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaalfridServer).DetectLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/maalfrid.Maalfrid/DetectLanguage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaalfridServer).DetectLanguage(ctx, req.(*DetectLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Maalfrid_serviceDesc = grpc.ServiceDesc{
	ServiceName: "maalfrid.Maalfrid",
	HandlerType: (*MaalfridServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectLanguage",
			Handler:    _Maalfrid_DetectLanguage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "maalfrid.proto",
}

func init() { proto.RegisterFile("maalfrid.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd8, 0x77, 0xb4, 0x24, 0x45,
	0xd9, 0xc7, 0x71, 0x96, 0xcb, 0x0b, 0xcb, 0xe5, 0x7d, 0xf7, 0xfd, 0x7a, 0x11, 0x45, 0x14, 0xc1,
	0x55, 0x10, 0x45, 0x57, 0x05, 0x73, 0xae, 0x99, 0xe9, 0xdb, 0xdd, 0xb7, 0xbb, 0xab, 0x7a, 0xab,
	0xbb, 0x67, 0x76, 0x46, 0x45, 0x17, 0x58, 0x10, 0x5d, 0xf2, 0x45, 0xc1, 0x48, 0x0e, 0x4b, 0xce,
	0x39, 0xe7, 0x9c, 0x73, 0xce, 0x39, 0xe7, 0x9c, 0x73, 0xce, 0x19, 0x3c, 0x53, 0xcf, 0x03, 0xe7,
	0xe8, 0x51, 0xff, 0xfb, 0xcc, 0xef, 0x79, 0xaa, 0x6f, 0x75, 0x57, 0xdf, 0x3e, 0x75, 0x6a, 0x74,
	0xda, 0x9a, 0xb3, 0x67, 0xcf, 0x5d, 0x6d, 0xbd, 0x35, 0x56, 0x9d, 0xb1, 0xce, 0x7a, 0x6b, 0x4f,
	0xae, 0x3d, 0x36, 0xf5, 0xa3, 0xdf, 0xd3, 0x97, 0x1f, 0x5d, 0xac, 0x33, 0x67, 0x72, 0xce, 0x2a,
	0x93, 0xf9, 0xec, 0xb5, 0x56, 0xdf, 0x60, 0xf6, 0xea, 0x73, 0xfc, 0x9c, 0x75, 0x37, 0x98, 0xb3,
	0xfe, 0xe4, 0xd8, 0xd8, 0xe8, 0x02, 0x93, 0x73, 0x36, 0x9c, 0x5c, 0x7c, 0xca, 0xd2, 0x53, 0x96,
	0x5b, 0xd8, 0x07, 0x4f, 0x7f, 0x62, 0x99, 0xd1, 0x45, 0xff, 0xb5, 0x7b, 0x9d, 0xb9, 0x1b, 0x8d,
	0xb5, 0x46, 0xa7, 0xce, 0xd5, 0x20, 0xf4, 0x4f, 0x5b, 0x61, 0xd9, 0x19, 0x1f, 0xff, 0xc5, 0x7f,
	0x33, 0x60, 0xc6, 0xc7, 0xbf, 0x3e, 0x1e, 0x37, 0x7d, 0xde, 0x32, 0xa3, 0x53, 0x3f, 0x8a, 0xc7,
	0x16, 0x19, 0x5d, 0xa8, 0xb1, 0x99, 0x75, 0x3d, 0xcb, 0x7c, 0x63, 0x0b, 0x8d, 0x8e, 0x58, 0xd7,
	0x62, 0x4a, 0x80, 0x75, 0xcc, 0x3f, 0x44, 0xc7, 0x58, 0x46, 0x86, 0xa8, 0x7a, 0x11, 0x0b, 0x0c,
	0x11, 0xd9, 0x98, 0xff, 0x19, 0x62, 0xdc, 0x1b, 0x16, 0x0c, 0xa5, 0xc2, 0xb0, 0x90, 0x60, 0x82,
	0xa9, 0x82, 0x88, 0x85, 0x87, 0x30, 0xad, 0x8c, 0xd1, 0x00, 0xe3, 0x59, 0x24, 0x60, 0xdc, 0xf3,
	0xbf, 0x01, 0x99, 0xe1, 0xff, 0x42, 0xf3, 0xcc, 0x94, 0x69, 0x21, 0x29, 0x12, 0xfe, 0x3f, 0xc0,
	0x1b, 0x10, 0xc4, 0x7c, 0x62, 0x88, 0xa4, 0x1f, 0x31, 0x16, 0x92, 0xaa, 0x60, 0xd1, 0x80, 0xae,
	0xe1, 0x93, 0x82, 0x88, 0xc5, 0x02, 0xfa, 0x05, 0x9f, 0x0a, 0x18, 0x44, 0x7c, 0x7a, 0x88, 0x96,
	0x29, 0x58, 0x5c, 0x90, 0xf1, 0x99, 0x30, 0xf9, 0xa6, 0x62, 0x89, 0x90, 0x44, 0x39, 0x9f, 0x15,
	0x58, 0x3e, 0x27, 0xf0, 0x2c, 0x19, 0x90, 0x56, 0x7c, 0x3e, 0xc0, 0x55, 0x2c, 0x15, 0xe0, 0x23,
	0x96, 0x0e, 0x68, 0x72, 0xbe, 0x30, 0x44, 0xd1, 0x37, 0x4c, 0x1f, 0xa2, 0x6d, 0x6a, 0xbe, 0x18,
	0x90, 0x18, 0xbe, 0x24, 0x88, 0x58, 0x26, 0x3c, 0xc3, 0xbe, 0x61, 0xd9, 0x21, 0x06, 0x89, 0xe3,
	0xcb, 0x52, 0xea, 0xb2, 0x5c, 0x80, 0xf3, 0x7c, 0x45, 0x50, 0xf1, 0xd5, 0x00, 0x1f, 0xb1, 0x7c,
	0xb8, 0x53, 0xdf, 0xe5, 0x6b, 0x21, 0x89, 0x2a, 0xbe, 0x3e, 0x44, 0xe9, 0x2b, 0x66, 0x84, 0xb5,
	0x48, 0xbb, 0x7c, 0x23, 0x5c, 0x39, 0xef, 0xf0, 0xcd, 0x90, 0x0c, 0x1c, 0xdf, 0x0a, 0xf7, 0x55,
	0x3a, 0x56, 0x08, 0xa8, 0x6a, 0x56, 0x0c, 0xe8, 0x45, 0x7c, 0x3b, 0x2c, 0x93, 0x71, 0x7c, 0x27,
	0x20, 0x9d, 0xe0, 0xbb, 0x02, 0xcb, 0xf7, 0x02, 0x9a, 0x9c, 0xef, 0x0f, 0x11, 0xe7, 0x31, 0x3f,
	0x18, 0x22, 0x33, 0x35, 0x3f, 0x0c, 0x57, 0x8e, 0x1a, 0x7e, 0x14, 0xae, 0x93, 0xe7, 0xfc, 0x38,
	0xf4, 0x78, 0xcb, 0x4f, 0x02, 0x9a, 0x09, 0x7e, 0x1a, 0xa6, 0x6a, 0x6a, 0x7e, 0x26, 0x68, 0xf8,
	0x79, 0x40, 0xd4, 0xc2, 0x08, 0x3c, 0xad, 0x80, 0xd4, 0xd2, 0x0e, 0x28, 0x1c, 0x9d, 0x80, 0xc6,
	0x12, 0x0d, 0x91, 0x5a, 0xc3, 0xb8, 0xa0, 0x43, 0x1c, 0x90, 0x47, 0x24, 0x32, 0x9f, 0x88, 0x34,
	0x24, 0x2d, 0xc7, 0x44, 0x40, 0x99, 0x91, 0x05, 0x74, 0x1c, 0x79, 0x40, 0x95, 0x53, 0x04, 0xd4,
	0x06, 0x1b, 0x90, 0x35, 0xb8, 0x21, 0x26, 0x4a, 0x4b, 0x19, 0x60, 0xba, 0xcc, 0x94, 0xfb, 0xca,
	0xf1, 0x02, 0x4b, 0x25, 0x68, 0xa8, 0x05, 0x15, 0x8d, 0x60, 0x40, 0x37, 0x20, 0x29, 0xe8, 0x05,
	0xa4, 0x19, 0xb3, 0x04, 0x96, 0xbe, 0xc0, 0x33, 0x08, 0x70, 0x05, 0xbf, 0x10, 0x58, 0x7e, 0x29,
	0xf0, 0xfc, 0x2a, 0xa0, 0xf1, 0xac, 0x24, 0x30, 0xfc, 0x7a, 0x88, 0xdc, 0xd4, 0xfc, 0x26, 0xa0,
	0x1e, 0x30, 0x3b, 0xa0, 0x89, 0x59, 0x39, 0x20, 0x2d, 0x58, 0x45, 0x60, 0x59, 0x55, 0x9a, 0x1d,
	0x73, 0x24, 0xa9, 0x59, 0x4d, 0x9a, 0x5b, 0xac, 0x2e, 0xa5, 0x2e, 0xbf, 0x95, 0xe7, 0xd3, 0x65,
	0x8d, 0xf0, 0x1e, 0x66, 0x1d, 0x7e, 0x17, 0x90, 0xc7, 0xfc, 0x3e, 0xa0, 0x32, 0xcc, 0x0d, 0x30,
	0x39, 0x6b, 0x4a, 0xa9, 0x66, 0xad, 0x00, 0x9f, 0xb2, 0xb6, 0x94, 0x3c, 0xeb, 0x08, 0x12, 0xd6,
	0x0d, 0x70, 0x96, 0xf5, 0xc2, 0xab, 0x65, 0x1a, 0xd6, 0x17, 0x74, 0x99, 0x0c, 0xe8, 0x44, 0x6c,
	0x10, 0x50, 0x39, 0xfe, 0x10, 0x10, 0x95, 0xfc, 0x51, 0x4a, 0x8e, 0x0d, 0xe5, 0xbb, 0xe1, 0xd9,
	0x28, 0x2c, 0x41, 0x9a, 0xf2, 0xa7, 0x90, 0xb4, 0x72, 0xfe, 0x3c, 0x84, 0x6b, 0xa7, 0xfc, 0x25,
	0x60, 0x22, 0xe5, 0xaf, 0xf2, 0x5f, 0xd0, 0xf0, 0xb7, 0x90, 0xf8, 0x82, 0xbf, 0x8f, 0x4d, 0x1d,
	0x22, 0x65, 0xe3, 0x29, 0x41, 0x55, 0xc5, 0x26, 0x41, 0xa5, 0xb1, 0x6c, 0x2a, 0xca, 0x53, 0x36,
	0x0b, 0x1a, 0x37, 0x15, 0x9b, 0x4b, 0xe6, 0x72, 0xb6, 0x10, 0x35, 0x15, 0x5b, 0x6a, 0xe6, 0xd9,
	0x2a, 0x68, 0x66, 0x13, 0xb1, 0x75, 0x90, 0x77, 0x09, 0xdb, 0x88, 0x1a, 0xcb, 0x3c, 0xcd, 0x2c,
	0xdb, 0x6a, 0x56, 0xb1, 0x5d, 0x50, 0x65, 0x2c, 0xdb, 0x8b, 0x7c, 0x87, 0x1d, 0x44, 0xb6, 0xc3,
	0x8e, 0xa2, 0xc2, 0xb1, 0x93, 0xf6, 0xc5, 0xec, 0xac, 0x7d, 0x25, 0xbb, 0x04, 0xc5, 0xb9, 0x61,
	0x57, 0x1d, 0x61, 0xd8, 0x4d, 0x94, 0x5a, 0x76, 0x17, 0xe5, 0x19, 0x7b, 0xa8, 0xba, 0xec, 0x29,
	0x72, 0x05, 0x7b, 0xa9, 0x6a, 0xf6, 0x16, 0x95, 0x86, 0x7d, 0x44, 0x8d, 0x65, 0x5f, 0x51, 0xcf,
	0xb0, 0x9f, 0xa8, 0xea, 0xb1, 0x7f, 0x50, 0x6d, 0x0a, 0x0e, 0x10, 0x45, 0x39, 0x07, 0x8a, 0xe2,
	0x8c, 0x83, 0x44, 0x89, 0xe1, 0x60, 0x51, 0xea, 0x39, 0x24, 0xa8, 0xe5, 0x3a, 0x1c, 0x2a, 0x59,
	0x93, 0x71, 0x98, 0x8e, 0xc8, 0x39, 0x5c, 0x9e, 0x69, 0x9a, 0x73, 0x84, 0x64, 0x95, 0xe5, 0x48,
	0x91, 0xb3, 0x1c, 0xa5, 0x23, 0x3c, 0x47, 0x6b, 0xd5, 0x71, 0x8c, 0xce, 0xa0, 0xe6, 0x58, 0x51,
	0x2f, 0xe5, 0x38, 0xcd, 0x12, 0x8e, 0x0f, 0x6a, 0xd2, 0x98, 0x13, 0x44, 0x99, 0xe7, 0x44, 0x91,
	0xef, 0x70, 0x92, 0x68, 0xd0, 0xe2, 0xe4, 0xa0, 0x6e, 0x64, 0x39, 0x45, 0x94, 0x46, 0x9c, 0x2a,
	0x72, 0x39, 0xa7, 0x05, 0xf5, 0x72, 0xcb, 0xe9, 0x41, 0xed, 0x7e, 0xc1, 0x19, 0x92, 0xb9, 0x9c,
	0x33, 0x65, 0xce, 0xbe, 0xcf, 0x59, 0x41, 0xb3, 0x12, 0xc7, 0xd9, 0x41, 0xfd, 0xb4, 0xc3, 0x39,
	0x22, 0xe7, 0x39, 0x37, 0x68, 0x90, 0x18, 0xce, 0x13, 0x35, 0x39, 0xe7, 0x07, 0x99, 0x76, 0xc4,
	0x05, 0xaa, 0x84, 0x0b, 0x45, 0x1d, 0xc3, 0x45, 0xaa, 0x3e, 0x17, 0x8b, 0xc6, 0x0d, 0x97, 0xa8,
	0x12, 0x2e, 0x15, 0xa5, 0x96, 0xcb, 0x44, 0x59, 0xc6, 0xe5, 0xa2, 0x3c, 0xe2, 0x0a, 0x55, 0xcc,
	0x95, 0xaa, 0x9a, 0xab, 0x44, 0x36, 0xe6, 0x6a, 0x55, 0xc9, 0x35, 0xa2, 0xd2, 0x70, 0xad, 0xc8,
	0xb7, 0xb9, 0x4e, 0x65, 0xb9, 0x5e, 0x55, 0x72, 0x83, 0xaa, 0xe6, 0x46, 0x55, 0x8f, 0x9b, 0x44,
	0x55, 0xcd, 0xcd, 0xa2, 0x3a, 0xe1, 0x16, 0x51, 0x53, 0x71, 0xab, 0xa8, 0x67, 0xb8, 0x4d, 0xd6,
	0xdc, 0x74, 0xb8, 0x5d, 0x95, 0x72, 0x87, 0x2a, 0xe7, 0x4e, 0x95, 0xe5, 0x2e, 0x55, 0xc5, 0xdd,
	0xaa, 0x9a, 0x7b, 0x44, 0xd1, 0x04, 0xf7, 0xaa, 0x0a, 0xee, 0x13, 0x25, 0x8e, 0xfb, 0x45, 0x69,
	0xc6, 0x03, 0x2a, 0xcb, 0x83, 0xa2, 0xdc, 0xf0, 0x90, 0xc8, 0xd6, 0x3c, 0x2c, 0xf2, 0x86, 0x47,
	0x44, 0x75, 0xc6, 0xa3, 0xa2, 0xc6, 0xf0, 0x98, 0x2a, 0xe6, 0x71, 0x51, 0xdf, 0xf2, 0x84, 0xac,
	0xb4, 0xe9, 0xf0, 0xa4, 0x2a, 0xe5, 0x29, 0x95, 0xe7, 0x69, 0x55, 0xc3, 0x33, 0xa2, 0xa8, 0xc5,
	0xb3, 0xaa, 0x9c, 0xe7, 0x44, 0x49, 0x8b, 0xe7, 0x55, 0x31, 0x2f, 0xa8, 0x32, 0x5e, 0x54, 0x15,
	0xbc, 0xa4, 0xb2, 0xbc, 0xac, 0x72, 0xbc, 0xa2, 0x2a, 0x79, 0x55, 0xe5, 0x79, 0x4d, 0xd5, 0xe7,
	0x75, 0x51, 0xd1, 0xe6, 0x0d, 0x91, 0x2b, 0x79, 0x53, 0x54, 0x46, 0xbc, 0xa5, 0x1a, 0xe7, 0x6d,
	0x55, 0xc9, 0x3b, 0x22, 0x9f, 0xf0, 0xae, 0xaa, 0xe4, 0x3d, 0x51, 0xd5, 0xe2, 0x7d, 0x51, 0x53,
	0xf1, 0x41, 0x50, 0xc7, 0x64, 0x7c, 0xa8, 0xf2, 0x6c, 0x3c, 0xbf, 0xa8, 0xcf, 0x26, 0xa2, 0x28,
	0x67, 0x53, 0x95, 0x65, 0x33, 0x51, 0xec, 0xd9, 0x5c, 0x94, 0x5a, 0xb6, 0x10, 0xb9, 0x94, 0x2d,
	0x45, 0xde, 0xb0, 0x95, 0xa8, 0x6a, 0xb1, 0xb5, 0xa8, 0x31, 0x6c, 0xa3, 0x2a, 0x98, 0x27, 0xea,
	0x37, 0x6c, 0x1b, 0x14, 0x8d, 0xa7, 0x6c, 0x27, 0x8a, 0xfb, 0x6c, 0x2f, 0xca, 0x0c, 0x3b, 0x88,
	0xf2, 0x59, 0xec, 0x28, 0xb2, 0x05, 0x3b, 0x89, 0x7a, 0x8e, 0x9d, 0xe7, 0x97, 0x6f, 0xb1, 0x65,
	0x17, 0x55, 0xcd, 0xae, 0xa2, 0xb4, 0x61, 0x37, 0x91, 0xb3, 0xec, 0x2e, 0xf2, 0x05, 0x7b, 0xa8,
	0x1c, 0x7b, 0xaa, 0x3c, 0x7b, 0xa9, 0x2a, 0xf6, 0x16, 0x35, 0x9e, 0x7d, 0x82, 0x62, 0x63, 0xd8,
	0x57, 0xd5, 0x67, 0x3f, 0x51, 0xcb, 0xb0, 0xbf, 0x28, 0x2a, 0x38, 0x40, 0x35, 0xe0, 0x40, 0x51,
	0x9a, 0x73, 0x90, 0xa8, 0x48, 0x38, 0x58, 0xe4, 0x12, 0x0e, 0x51, 0x59, 0x0e, 0x55, 0x79, 0x0e,
	0x53, 0xd5, 0x1c, 0x2e, 0xf2, 0x2d, 0x8e, 0x50, 0xb5, 0x39, 0x52, 0x54, 0xf5, 0x38, 0x4a, 0xd4,
	0x4b, 0x39, 0x3a, 0x28, 0x31, 0x29, 0xc7, 0xa8, 0x7a, 0x1c, 0x2b, 0x4a, 0x73, 0x8e, 0x53, 0x15,
	0x1c, 0xaf, 0xaa, 0x39, 0x41, 0x54, 0x58, 0x4e, 0x14, 0x55, 0x2d, 0x4e, 0x12, 0x35, 0x25, 0x27,
	0x07, 0xa5, 0x2d, 0xc3, 0x29, 0xa2, 0x09, 0xc7, 0xa9, 0xa2, 0xdc, 0x71, 0x9a, 0xc8, 0xb6, 0x39,
	0x5d, 0x15, 0x71, 0x86, 0x2a, 0xe1, 0x4c, 0x91, 0x37, 0x9c, 0xa5, 0x72, 0x9c, 0x1d, 0x34, 0xd1,
	0x72, 0x9c, 0x23, 0x2a, 0x3d, 0xe7, 0x8a, 0x7c, 0x8b, 0xf3, 0x82, 0x32, 0x63, 0x38, 0x5f, 0xd5,
	0xe2, 0x02, 0x55, 0x9b, 0x0b, 0x55, 0x05, 0x17, 0xa9, 0x3c, 0x17, 0xab, 0x7a, 0x5c, 0x22, 0x6a,
	0x75, 0xb8, 0x54, 0x94, 0x18, 0x2e, 0x53, 0xa5, 0x5c, 0xae, 0x72, 0x5c, 0x21, 0x2a, 0x5a, 0x5c,
	0x29, 0x72, 0x19, 0x57, 0xa9, 0x2a, 0xae, 0x16, 0x95, 0x11, 0xd7, 0x88, 0x7c, 0x9b, 0x6b, 0x55,
	0x39, 0xd7, 0xa9, 0x1c, 0xd7, 0xab, 0x1a, 0x6e, 0x10, 0x35, 0x05, 0x37, 0xaa, 0x6a, 0x6e, 0x0a,
	0xca, 0x4d, 0x87, 0x9b, 0x55, 0x09, 0xb7, 0xa8, 0x0a, 0x6e, 0x15, 0x45, 0x03, 0x6e, 0x13, 0xb9,
	0x9c, 0xdb, 0x55, 0x03, 0xee, 0x10, 0x35, 0x86, 0x3b, 0x55, 0x29, 0x77, 0xa9, 0x2c, 0x77, 0xab,
	0x1c, 0xf7, 0xa8, 0x2a, 0xee, 0x0d, 0x2a, 0x4c, 0x87, 0xfb, 0x54, 0x31, 0xf7, 0xab, 0x52, 0x1e,
	0x50, 0x65, 0x3c, 0xa8, 0xb2, 0x3c, 0xa4, 0x2a, 0x79, 0x58, 0x55, 0xf1, 0x88, 0xa8, 0x33, 0xce,
	0xa3, 0x2a, 0xcf, 0x63, 0xa2, 0xc8, 0xf2, 0xb8, 0x28, 0x36, 0x3c, 0x21, 0x4a, 0xdb, 0x3c, 0xa9,
	0xb2, 0x3c, 0xa5, 0xaa, 0x78, 0x5a, 0x94, 0x25, 0x3c, 0x23, 0xb2, 0x6d, 0x9e, 0x55, 0xa5, 0x3c,
	0xa7, 0x72, 0x3c, 0x2f, 0x72, 0x09, 0x2f, 0xa8, 0x2a, 0x5e, 0x14, 0x35, 0x39, 0x2f, 0xa9, 0x2c,
	0x2f, 0xab, 0x2a, 0x5e, 0x11, 0xf5, 0x72, 0x5e, 0x55, 0x79, 0x5e, 0x13, 0xf5, 0x2d, 0xaf, 0xab,
	0xba, 0xbc, 0x11, 0x64, 0x4d, 0xc2, 0x9b, 0xaa, 0x94, 0xb7, 0x54, 0x25, 0x6f, 0x8b, 0x3a, 0x15,
	0xef, 0x88, 0xa2, 0x1e, 0xef, 0x8a, 0x52, 0xc3, 0x7b, 0xaa, 0x36, 0xef, 0xab, 0x1a, 0x3e, 0x10,
	0xb9, 0x98, 0x0f, 0x55, 0x96, 0x8d, 0x47, 0x82, 0x66, 0x3a, 0x36, 0x11, 0x35, 0x2d, 0x36, 0x15,
	0xf5, 0xda, 0x6c, 0x26, 0xea, 0x17, 0x6c, 0xae, 0xb2, 0x6c, 0xa1, 0x72, 0x6c, 0x29, 0x1a, 0xa4,
	0x6c, 0x35, 0x22, 0xbb, 0x48, 0xc3, 0xd6, 0xa2, 0xda, 0xb0, 0x8d, 0xca, 0x31, 0x6f, 0x44, 0x76,
	0x96, 0x86, 0x6d, 0x55, 0x31, 0xdb, 0xa9, 0x72, 0xb6, 0x57, 0x15, 0xec, 0xa0, 0x2a, 0xd9, 0x51,
	0xd5, 0xb0, 0x93, 0x28, 0x72, 0xec, 0x2c, 0x4a, 0x52, 0x76, 0x51, 0x59, 0x76, 0x15, 0x39, 0xcb,
	0x6e, 0x22, 0x6f, 0xd8, 0x5d, 0xe5, 0xd8, 0x23, 0xc8, 0x9b, 0x09, 0xf6, 0x54, 0x95, 0xec, 0xa5,
	0xf2, 0xec, 0x2d, 0x72, 0x86, 0x7d, 0x54, 0x05, 0xfb, 0x8a, 0x9a, 0x92, 0xfd, 0x46, 0x64, 0xdf,
	0xd9, 0x61, 0x7f, 0x55, 0xc2, 0x01, 0xaa, 0x94, 0x03, 0x55, 0x39, 0x07, 0xa9, 0x0a, 0x0e, 0x56,
	0x55, 0x1c, 0xa2, 0xaa, 0x39, 0x54, 0xd4, 0xb6, 0x1c, 0xa6, 0x72, 0x1c, 0x2e, 0x8a, 0x72, 0x8e,
	0x50, 0x15, 0x1c, 0x29, 0x8a, 0x0d, 0x47, 0xa9, 0x2c, 0x47, 0x8b, 0x12, 0xcb, 0x31, 0xa2, 0xb4,
	0xc3, 0xb1, 0x2a, 0xc7, 0x71, 0xaa, 0x9a, 0xe3, 0x45, 0xb9, 0xe1, 0x04, 0x51, 0x91, 0x72, 0xa2,
	0xca, 0x72, 0x92, 0xaa, 0xe2, 0x64, 0x91, 0xcd, 0x38, 0x45, 0xe4, 0x62, 0x4e, 0x55, 0x59, 0x4e,
	0x13, 0x79, 0xcb, 0xe9, 0x2a, 0xcf, 0x19, 0xa2, 0xca, 0x70, 0xa6, 0xa8, 0xc9, 0x38, 0x4b, 0x55,
	0x71, 0xb6, 0x6a, 0x16, 0xe7, 0x88, 0xfa, 0x6d, 0xce, 0x55, 0x79, 0xce, 0x1b, 0x91, 0xfd, 0x69,
	0xca, 0xf9, 0xa2, 0xa8, 0xe0, 0x02, 0x95, 0xe7, 0x42, 0x55, 0xcd, 0x45, 0xa2, 0x34, 0xe6, 0x62,
	0x55, 0x97, 0x4b, 0x44, 0x59, 0xce, 0xa5, 0xa2, 0x3c, 0xe1, 0x32, 0x55, 0xca, 0xe5, 0xa2, 0x22,
	0xe1, 0x0a, 0x91, 0x8b, 0xb9, 0x52, 0x54, 0xa6, 0x5c, 0x25, 0xaa, 0x52, 0xae, 0x16, 0x35, 0x05,
	0xd7, 0xa8, 0x4a, 0xae, 0x55, 0xd5, 0x5c, 0x27, 0xea, 0xe6, 0x5c, 0x2f, 0xea, 0x77, 0xb9, 0x21,
	0xa8, 0xe9, 0x14, 0xdc, 0x28, 0x8a, 0x0d, 0x37, 0x89, 0x8a, 0x16, 0x37, 0x8b, 0x6c, 0x87, 0x5b,
	0x82, 0xba, 0x26, 0xe5, 0x56, 0x91, 0xab, 0xb9, 0x2d, 0xa8, 0x67, 0x32, 0x6e, 0x57, 0xe5, 0xdc,
	0xa1, 0xf2, 0xdc, 0xa9, 0xaa, 0xb8, 0x4b, 0x14, 0x59, 0xee, 0x0e, 0x9a, 0x65, 0x72, 0xee, 0x09,
	0xea, 0x1b, 0xc7, 0xbd, 0xaa, 0x92, 0xfb, 0x44, 0x65, 0xc6, 0xfd, 0x41, 0x03, 0x53, 0xf2, 0x80,
	0xa8, 0x95, 0xf3, 0xa0, 0x28, 0xb2, 0x3c, 0x24, 0x8a, 0x13, 0x1e, 0x16, 0xd9, 0x0e, 0x8f, 0x88,
	0x1a, 0xcb, 0xa3, 0xa2, 0x59, 0xb3, 0x78, 0x4c, 0x34, 0x30, 0x3c, 0x3e, 0xb2, 0xc2, 0x4a, 0xa3,
	0x53, 0x0b, 0x3d, 0xbf, 0x1a, 0xf3, 0xa3, 0xd3, 0xfe, 0xf9, 0x08, 0x6b, 0x6c, 0xa9, 0xff, 0x7c,
	0xb8, 0x15, 0xce, 0xce, 0x96, 0x58, 0xf2, 0xbf, 0x9e, 0x7e, 0x4d, 0x9f, 0x6f, 0xe5, 0x05, 0xc3,
	0x31, 0xdc, 0x8a, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0x69, 0xb3, 0xa7, 0x25, 0x98, 0x13, 0x00,
	0x00,
}
